// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ComposableMapJs = require("../node_modules/react-simple-maps/lib/ComposableMap.js");

function make(projectionConfig, $staropt$star, $staropt$star$1, children) {
  var width = $staropt$star ? $staropt$star[0] : 100;
  var height = $staropt$star$1 ? $staropt$star$1[0] : 100;
  var partial_arg = /* Some */[height];
  var partial_arg$1 = /* Some */[width];
  return ReasonReact.wrapJsForReason(ComposableMapJs.default, (function () {
                var tmp = {
                  projectionConfig: projectionConfig
                };
                if (partial_arg$1) {
                  tmp.width = partial_arg$1[0];
                }
                if (partial_arg) {
                  tmp.height = partial_arg[0];
                }
                return tmp;
              }), children);
}

exports.make = make;
/* ReasonReact Not a pure module */
