// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var GeographiesJs = require("../node_modules/react-simple-maps/lib/Geographies.js");

function make($staropt$star, geography, children) {
  var disableOptimization = $staropt$star ? $staropt$star[0] : false;
  return ReasonReact.wrapJsForReason(GeographiesJs.default, {
              disableOptimization: disableOptimization,
              geography: geography
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
