// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var GeographyJs = require("../node_modules/react-simple-maps/lib/Geography.js");

function make(geography, projection, style, children) {
  return ReasonReact.wrapJsForReason(GeographyJs.default, {
              geography: geography,
              projection: projection,
              style: style
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
