// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var MarkersJs = require("../node_modules/react-simple-maps/lib/Markers.js");

function make(children) {
  return ReasonReact.wrapJsForReason(MarkersJs.default, { }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
