// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var MarkerJs = require("../node_modules/react-simple-maps/lib/Marker.js");

function make(marker, style, children) {
  return ReasonReact.wrapJsForReason(MarkerJs.default, {
              style: style,
              marker: marker
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
