// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ZoomableGroupJs = require("../node_modules/react-simple-maps/lib/ZoomableGroup.js");

function make($staropt$star, children) {
  var disablePanning = $staropt$star ? $staropt$star[0] : false;
  return ReasonReact.wrapJsForReason(ZoomableGroupJs.default, {
              disablePanning: disablePanning
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
